image: odclive/alpine_build_arm:latest

stages:
  - build
  - test

build_backend:
  stage: build
  script:
    - make
    - ./mincamlc asml/call.asml

test_arm:
  stage: test
  script:
    - cd ARM
    - make
    - make test
