image: odclive/alpine_build_arm:latest

stages:
  - backend

build_backend:
  stage: backend
  script:
    - make
    - ./mincamlc asml/call.asml
  artifacts:


test_arm:
  stage: backend
  before_script:
    - make
    - ./mincamlc asml/call.asml
  script:
    - cd ARM
    - make
    - make test
