image: odclive/alpine_build_arm:latest

stages:
  - build_compiler
  - tests

test_build:
  stage: build_compiler
  script:
    - make

typechecking:
  stage: tests
  script:
    - make test_typechecking

asml_gen:
  stage: tests
  script:
    - make test_asml_gen
