image: odclive/alpine_build_arm:latest

stages:
  - backend

build_backend:
  stage: backend
  script:
    - make
    - ./mincamlc asml/call.asml

test_arm:
  stage: backend
  script:
    - cd ARM
    - make
    - make test
